### PR TITLE
Add newline to the output

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
* and other small fixes

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
I was comparing this with my go implementation https://github.com/gunnarmorling/1brc/discussions/67 and saw different sha256 hash value due to missing newline at the end of the result, otherwise it matches.

**Comment by lehuyduc** [comment]
Does other solution use `\n` at the end of output? I think the reference code doesn't add `\n`, I don't see it it the ref output file.

Edit: oh it does. I wonder why my file doesn't have it.

**Comment by lehuyduc** [comment]
Fixed. Thanks!

**Comment by AlexanderYastrebov** [comment]
Maybe you want to include other changes from this PR. E.g. run_cpp.sh is not executable and rm main complains after clone and its nice to have no trailing whitespaces.

**Comment by lehuyduc** [comment]
> Maybe you want to include other changes from this PR. E.g. run_cpp.sh is not executable and rm main complains after clone and its nice to have no trailing whitespaces. I didn't merge because I already manually added `\n` to all files then push, and don't want to fix merge conflict :D 

Thanks, I've just made a new commit that changes `run_cpp.sh` so `rm` doesn't complain. And remove whitespaces.

`result.txt` file is completely different, I think it's from a different input.

**Pull request closed without merging**
